language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

install:
    - composer install --prefer-dist
    - chmod +x ./bin/php_no_xdebug

script:
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array --parameters="[10]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array --parameters="[100]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array --parameters="[1000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array --parameters="[10000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array --parameters="[100000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch --parameters="[10]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch --parameters="[100]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch --parameters="[1000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch --parameters="[10000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch --parameters="[100000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll --parameters="[10]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll --parameters="[100]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll --parameters="[1000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll --parameters="[10000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll --parameters="[100000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array2 --parameters="[10]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array2 --parameters="[100]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array2 --parameters="[1000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array2 --parameters="[10000]"
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array2 --parameters="[100000]"
